_wandb:
    value:
        cli_version: 0.26.1
        e:
            qg6bfeecxfkth0uos5cql8pfpjvnstmt:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    macModel: MacBookPro18,1
                    memoryGb: 16
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "12884901888"
                args:
                    - --data
                    - Small_LI
                    - --model
                    - gin
                    - --n_epochs
                    - "20"
                    - --emlps
                    - --reverse_mp
                    - --ports
                    - --ego
                    - --tqdm
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "851464257536"
                email: jacoblourie@gmail.com
                executable: /opt/anaconda3/envs/multignn-restored/bin/python
                git:
                    commit: 030d9361d4c5ffb85ba7696123cadaf114e696d9
                    remote: https://github.com/jlowritescode/Multi-GNN.git
                host: Jons-MacBook-Pro-2.local
                memory:
                    total: "17179869184"
                os: macOS-26.4.1-arm64-arm-64bit
                program: /Users/jonlourie/GNN_project_laundry/Multi-GNN/main.py
                python: CPython 3.9.25
                root: /Users/jonlourie/GNN_project_laundry/Multi-GNN
                startedAt: "2026-08-10T20:01:06.574559Z"
                writerId: qg6bfeecxfkth0uos5cql8pfpjvnstmt
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 53
                - 77
            "2":
                - 1
                - 5
                - 53
                - 77
            "3":
                - 2
                - 16
                - 61
            "4": 3.9.25
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
batch_size:
    value: 8192
data:
    value: Small_LI
dropout:
    value: 0.00983468338330501
epochs:
    value: 20
final_dropout:
    value: 0.10527690625126304
loss:
    value: ce
lr:
    value: 0.006213266113989207
model:
    value: gin
n_gnn_layers:
    value: 2
n_heads:
    value: null
n_hidden:
    value: 66.00315515631006
num_neighbors:
    value:
        - 100
        - 100
w_ce1:
    value: 1.0000182882773443
w_ce2:
    value: 6.275014431494497
